// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/mnabil1718/taskflow/internal/bootstrap"
	"github.com/mnabil1718/taskflow/internal/config"
	"github.com/mnabil1718/taskflow/internal/handler"
	"github.com/mnabil1718/taskflow/internal/notifier"
	"github.com/mnabil1718/taskflow/internal/repository"
	"github.com/mnabil1718/taskflow/internal/service"
)

import (
	_ "github.com/mnabil1718/taskflow/docs"
)

// Injectors from wire.go:

func initServer(cfg *config.Config, db *sql.DB) *bootstrap.Server {
	userRepository := repository.NewUserRepository(db)
	tokenRepository := repository.NewTokenRepository(db)
	authService := service.NewAuthService(userRepository, tokenRepository, cfg)
	healthHandler := handler.NewHealthHandler()
	authHandler := handler.NewAuthHandler(authService)
	projectRepository := repository.NewProjectRepository(db)
	projectService := service.NewProjectService(projectRepository, userRepository)
	projectHandler := handler.NewProjectHandler(projectService)
	taskRepository := repository.NewTaskRepository(db)
	hub := notifier.NewHub()
	notificationRepository := repository.NewNotificationRepository(db)
	notificationService := service.NewNotificationService(notificationRepository, hub)
	taskService := service.NewTaskService(taskRepository, projectRepository, notificationService)
	taskHandler := handler.NewTaskHandler(taskService)
	dashboardRepository := repository.NewDashboardRepository(db)
	dashboardService := service.NewDashboardService(dashboardRepository)
	dashboardHandler := handler.NewDashboardHandler(dashboardService)
	notificationHandler := handler.NewNotificationHandler(notificationService, hub)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	trashRepository := repository.NewTrashRepository(db)
	trashService := service.NewTrashService(trashRepository)
	trashHandler := handler.NewTrashHandler(trashService)
	app := bootstrap.NewApp(cfg, authService, healthHandler, authHandler, projectHandler, taskHandler, dashboardHandler, notificationHandler, userHandler, trashHandler)
	deadlineScheduler := service.NewDeadlineScheduler(taskRepository, projectRepository, notificationService)
	server := bootstrap.NewServer(cfg, app, deadlineScheduler)
	return server
}
