// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/mnabil1718/taskflow/internal/bootstrap"
	"github.com/mnabil1718/taskflow/internal/config"
	"github.com/mnabil1718/taskflow/internal/handler"
)

// Injectors from wire.go:

func initServer(cfg *config.Config) *bootstrap.Server {
	healthHandler := handler.NewHealthHandler()
	app := bootstrap.NewApp(healthHandler)
	server := bootstrap.NewServer(cfg, app)
	return server
}
